# Generated by Django 4.2 on 2023-10-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='article',
            name='pubished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
