# Generated by Django 4.2 on 2023-10-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_content_article_body_remove_article_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pubished_at',
            new_name='published_at',
        ),
    ]
